<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<Version>0.1.8</Version>
		<Authors>Pasha</Authors>
		<Company>SUS Digital Productions</Company>
		<Product>SUS.AtomicTools.Client</Product>
		<PackageId>SUS.AtomicTools.Client</PackageId>
		<Title>SUS Atomic Tools Client</Title>
		<PackageTags>atomictools;blockchain;wax;eos;nft;api-client</PackageTags>
		<Description>Open source .NET client for AtomicTools API. Provides strongly-typed, fluent API access to all AtomicTools endpoints. Brought to you by SUS Digital Productions.</Description>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/SUS-Digital-Productions/sus-atomic-client</PackageProjectUrl>
		<RepositoryUrl>https://github.com/SUS-Digital-Productions/sus-atomic-client</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageIcon>icon.png</PackageIcon>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="SUS.Atomic.Base" Version="0.1.8" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="..\..\README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

</Project>
